version: '3.5'

services:
        postgres:
          image: postgres:latest
          environment: 
            - POSTGRES_DB=resources
            - POSTGRES_USER=lucho
            - POSTGRES_PASSWORD =admin123
            - POSTGRES_HOST_AUTH_METHOD=trust
          ports: 
            - 5432:5432
          volumes:
            - ./postgres_data:/var/lib/postgres/data

        pgadmin:
            image: dpage/pgadmin4
            environment:
            - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
            - PGADMIN_DEFAULT_PASSWORD=admin
            ports:
            - 5050:80